jwt:
  secret: hungpass
  signOptions:
    expiresIn: 7days

redis:
  host: 127.0.0.1
  port: 6379

typeorm:
  host: 127.0.0.1
  port: 3306
  logging: true
  database: namera_drive
  username: namera_drive
  password: namera_drive
  synchronize: true

storage:
  root: /home/hungtcs/Temp/NameraDriveRoot
  trashPath: .namera/trash
  uploadPath: .namera/upload
  thumbnailsPath: .namera/thumbnails
