jwt:
  secret: hungpass
  signOptions:
    expiresIn: 7days

typeorm:
  host: 127.0.0.1
  port: 3306
  logging: true
  database: namera_drive
  username: namera_drive
  password: namera_drive
  synchronize: true

storage:
  engine:
    type: local
    root: /home/hungtcs/Temp/NameraDriveRoot
    # type: minio
    # username: minio
    # password: minio
  trashPath: .namera/trash
  uploadPath: .namera/upload
